[package]
name = "chess"
version = "0.1.0"
authors = ["tomerh"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
dialoguer = "0.5.0"
